- hosts: '{{ env_host_list }}'
  remote_user: root
  vars:
    - package_name: '{{ env_package_name }}'
    - dest_package_path: "/mds6800/packages/"
  tasks:
    - name: excute hostname command
      shell: hostname